name: Release build

on:
  workflow_dispatch

jobs:
  build:
    name: Release build
    strategy:
      matrix:
        include:
          - platform: 2
            platform_name: ios
          - platform: 3
            platform_name: tvos
          - platform: 7
            platform_name: iossimulator
          - platform: 8
            platform_name: tvossimulator

    runs-on: macos-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@main

      - name: Checkout repository submodules
        run: git submodule update --init --recursive

      - name: Get gl4es latest commit hash
        id: gl4es-sha
        run: echo "sha=$(git ls-remote https://github.com/PojavLauncherTeam/gl4es-114-extra refs/heads/master | grep -io '^\S*')" >> $GITHUB_OUTPUT
        shell: bash

      - name: Cache gl4es
        uses: actions/cache@main
        if: false
        id: gl4es-cache
        with:
          path: gl4es/libs
          key: gl4es-holy-ios-shared-2-${{ steps.gl4es-sha.outputs.sha }}

      - name: Get JRE8
        uses: dawidd6/action-download-artifact@v21
        with:
          github_token: ${{secrets.GITHUB_TOKEN}}
          repo: PojavLauncherTeam/android-openjdk-build-multiarch
          workflow: build.yml
          workflow_conclusion: success
          path: depends
          name: jre8-ios-aarch64

      - name: Get JRE17
        uses: dawidd6/action-download-artifact@v21
        with:
          github_token: ${{secrets.GITHUB_TOKEN}}
          repo: PojavLauncherTeam/android-openjdk-build-multiarch
          workflow: build.yml
          workflow_conclusion: success
          path: depends
          name: jre17-ios-aarch64

      - name: Get JRE21
        uses: dawidd6/action-download-artifact@v21
        with:
          github_token: ${{secrets.GITHUB_TOKEN}}
          repo: PojavLauncherTeam/android-openjdk-build-multiarch
          workflow: build.yml
          workflow_conclusion: completed
          path: depends
          name: jre21-ios-aarch64

      - name: Set up JDK 8
        uses: actions/setup-java@v4
        with:
          java-version: "8"
          distribution: "zulu"

      - name: Install GNU make
        run: brew install make

      - name: Install ldid
        run: brew install ldid

      - name: Build for ${{ matrix.platform_name }}
        run: |
          export PATH=/opt/homebrew/bin:$PATH
          export RUNNER=1
          export BOOTJDK="$JAVA_HOME/bin"
          if [ "${{ matrix.platform_name }}" == "ios" ]; then
            gmake -j$(sysctl -n hw.ncpu) dsym package PLATFORM=${{ matrix.platform }} BOOTJDK=$BOOTJDK
            gmake -j$(sysctl -n hw.ncpu) dsym package PLATFORM=${{ matrix.platform }} TROLLSTORE_JIT_ENT=1 BOOTJDK=$BOOTJDK
          elif [ "${{ matrix.platform_name }}" == "tvos" ]; then
            gmake -j$(sysctl -n hw.ncpu) dsym package PLATFORM=${{ matrix.platform }} TROLLSTORE_JIT_ENT=1 BOOTJDK=$BOOTJDK
          else
            gmake -j$(sysctl -n hw.ncpu) dsym package PLATFORM=${{ matrix.platform }} BOOTJDK=$BOOTJDK
          fi

      - name: Upload regular ipa
        uses: actions/upload-artifact@main
        with:
          name: net.kdt.pojavlauncher-${{ matrix.platform_name }}.ipa
          path: artifacts/net.kdt.pojavlauncher-*-${{ matrix.platform_name }}.ipa

      - name: Upload regular tipa
        uses: actions/upload-artifact@main
        with:
          name: net.kdt.pojavlauncher-${{ matrix.platform_name }}.tipa
          path: artifacts/net.kdt.pojavlauncher-*-${{ matrix.platform_name }}-trollstore.tipa

      - name: Upload PojavLauncher.dSYM
        uses: actions/upload-artifact@main
        if: matrix.platform_name == 'ios'
        with:
          name: PojavLauncher.dSYM
          path: artifacts/PojavLauncher.dSYM
