name: Release build

on:
  workflow_dispatch

jobs:
  build:
    name: Release build
    strategy:
      matrix:
        include:
          - platform: 2
            platform_name: ios

    runs-on: macos-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@main

      - name: Checkout repository submodules
        run: git submodule update --init --recursive

      - name: Get gl4es latest commit hash
        id: gl4es-sha
        run: echo "sha=$(git ls-remote https://github.com/PojavLauncherTeam/gl4es-114-extra refs/heads/master | grep -io '^\S*')" >> $GITHUB_OUTPUT
        shell: bash

      - name: Cache gl4es
        uses: actions/cache@main
        if: false
        id: gl4es-cache
        with:
          path: gl4es/libs
          key: gl4es-holy-ios-shared-2-${{ steps.gl4es-sha.outputs.sha }}

      - name: Set up JDK 8
        uses: actions/setup-java@v4
        with:
          java-version: "8"
          distribution: "zulu"

      - name: Install GNU make
        run: brew install make

      - name: Install ldid
        run: brew install ldid

      - name: Build for ${{ matrix.platform_name }}
        run: |
          export PATH=/opt/homebrew/bin:$PATH
          export RUNNER=1
          export BOOTJDK="$JAVA_HOME/bin"
          gmake -j$(sysctl -n hw.ncpu) dsym package PLATFORM=${{ matrix.platform }} BOOTJDK=$BOOTJDK
          gmake -j$(sysctl -n hw.ncpu) dsym package PLATFORM=${{ matrix.platform }} TROLLSTORE_JIT_ENT=1 BOOTJDK=$BOOTJDK

      - name: Upload regular ipa
        uses: actions/upload-artifact@main
        with:
          name: org.angelauramc.amethyst-${{ matrix.platform_name }}.ipa
          path: artifacts/org.angelauramc.amethyst-*-${{ matrix.platform_name }}.ipa

      - name: Upload regular tipa
        uses: actions/upload-artifact@main
        with:
          name: org.angelauramc.amethyst-${{ matrix.platform_name }}-trollstore.tipa
          path: artifacts/org.angelauramc.amethyst-*-${{ matrix.platform_name }}-trollstore.tipa

      - name: Upload slimmed ipa
        uses: actions/upload-artifact@main
        with:
          name: org.angelauramc.amethyst.slimmed-${{ matrix.platform_name }}.ipa
          path: artifacts/org.angelauramc.amethyst.slimmed-*-${{ matrix.platform_name }}.ipa

      - name: Upload AngelAuraAmethyst.dSYM
        uses: actions/upload-artifact@main
        with:
          name: AngelAuraAmethyst.dSYM
          path: artifacts/AngelAuraAmethyst.dSYM
